print ("Total Marks of Each Subject = 100")
Physics = int(input("Marks in Physics ="))
Chemistry = int(input("Marks in Chemistry = "))
Maths = int(input("Marks in Maths = "))
English = int(input("Marks in English = "))
Physical_Education = int(input("Marks in Physical_Education = "))