name = input("Enter your Name = ")
# age = int(input("Enter your Age = "))
# show_time = input("tpye Morning, Mid_Day, Evening = ")
# ticket_price = int(input("Ticket price"))
# student = input("Type Y or N =")
# discount_age = (age < 18) and (ticket_price-(20/100*ticket_price)) or (50 >= age >= 18) and (ticket_price-(10/100*ticket_price)) or (age >50) and (ticket_price-(30/100*ticket_price))
# discount_show_time = (show_time == "morning") and (ticket_price-(30/100*ticket_price)) or (show_time == "MidDay") and (ticket_price-(20/100*ticket_price)) or (show_time == "Evening") and (ticket_price-(10/100*ticket_price))
# discount_student = (student == "Y") and (ticket_price-(20/100*ticket_price)) or (student == "N" ) and (ticket_price-(10/100*ticket_price))

# final_price = ("Final Price of your movie ticket = " , ticket_price - (discount_age + discount_show_time + discount_student))
# print(name ,age , show_time , ticket_price , student , final_price, sep="\n")